#cloud-config
autoinstall:
    version: 1
    identity:
        hostname: dsk-ubuntu-ghs
        username: ghsilva
        password: "$6$y1mmtJ4OMYmyad/S$UO49nvdKKW23GAozH9uk.3Qg2nkJIE2YesbBZy.q6ebrqG0q8ftj9/EiSOGKq4C5ssL5h90wKQZ99BMwqJEFl1"
