#cloud-config
autoinstaller:
  version: 1
  source:
    id: ubuntu-desktop-minimal
  
  locale: en_US.UTF-8
  keyboard:
    layout: br
  timezone: America/Sao_Paulo

  network:
    version: 2
    ethernets: 
      enp1s0:
        dhcp4: true
  
  identity: 
    hostname: dsk-ubuntu-ghs
    username: ghsilva
    password: "$6$y1mmtJ4OMYmyad/S$UO49nvdKKW23GAozH9uk.3Qg2nkJIE2YesbBZy.q6ebrqG0q8ftj9/EiSOGKq4C5ssL5h90wKQZ99BMwqJEFl1"

