#cloud-config
autoinstall:
    version: 1
    interactive-sections:
        - storage
    source:
        id: ubuntu-desktop-minimal
    identity:
        hostname: dsk-ubuntu-ghs
        username: ghsilva
        password: "$6$y1mmtJ4OMYmyad/S$UO49nvdKKW23GAozH9uk.3Qg2nkJIE2YesbBZy.q6ebrqG0q8ftj9/EiSOGKq4C5ssL5h90wKQZ99BMwqJEFl1"
    locale: en_US.UTF-8
    keyboard:
        layout: br
    timezone: America/Sao_Paulo
    snaps:
        - name: kubectl
          classic: true
        - name: terraform
          classic: true
        - name: chromium
          classic: true
        - name: codium
          classic: true
        - name: aws-cli
          classic: true
        - name: docker
          classic: true
        - name: go
          channel: 1.18/stable
          classic: true
        - name: dbeaver-ce
          classic: true
        - name: intellij-idea-community
          classic: true
        - name: spotify
          classic: true
    packages:
        - openjdk-17-jre
        - ansible
        - putty
        - nmap
        - zsh
        - git
